import { createFileRoute } from "@tanstack/react-router";
import { Check, Clock3, FileText, ShieldCheck, UserRound, X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHeader, StatCard } from "@/components/kaksha/page-ui";
import { resources } from "@/lib/mock-data";
import { pageMeta } from "@/lib/route-meta";

type Status="Pending"|"Approved"|"Rejected";
export const Route=createFileRoute("/admin")({head:()=>pageMeta("Admin Dashboard","Preview Kaksha Hub moderation statistics and pending resource reviews."),component:Admin});
function Admin(){const [rows,setRows]=useState(resources.slice(0,4).map(resource=>({...resource,status:"Pending" as Status})));const update=(id:string,status:Status)=>setRows(current=>current.map(row=>row.id===id?{...row,status}:row));return <><PageHeader eyebrow="Moderation workspace" title="Admin Dashboard" description="Review contribution quality and monitor the health of the resource library. All actions are mock-only."/><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard icon={FileText} label="Total resources" value="4,862" detail="+124 this month"/><StatCard icon={Clock3} label="Pending review" value={String(rows.filter(r=>r.status==="Pending").length)} detail="Needs attention"/><StatCard icon={UserRound} label="Contributors" value="1,284" detail="Across all branches"/><StatCard icon={ShieldCheck} label="Approval rate" value="91%" detail="Last 30 days"/></div><section className="mt-12"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-primary">Review queue</p><h2 className="mt-1 font-display text-2xl font-extrabold">Pending Contributions</h2></div></div><div className="mt-6 overflow-x-auto rounded-lg border border-border bg-card shadow-card"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-secondary text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-4">Resource</th><th className="px-5 py-4">Contributor</th><th className="px-5 py-4">Branch</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t border-border"><td className="px-5 py-4"><strong className="block max-w-xs">{row.title}</strong><span className="text-xs text-muted-foreground">{row.type} · {row.code}</span></td><td className="px-5 py-4">{row.contributor}</td><td className="px-5 py-4">{row.branch} · S{row.semester}</td><td className="px-5 py-4"><span className={`rounded-md px-2 py-1 text-xs font-bold ${row.status==="Approved"?"bg-primary/10 text-primary":row.status==="Rejected"?"bg-destructive/10 text-destructive":"bg-highlight/15 text-highlight-strong"}`}>{row.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Button size="sm" onClick={()=>update(row.id,"Approved")}><Check/>Approve</Button><Button size="sm" variant="outline" onClick={()=>update(row.id,"Rejected")}><X/>Reject</Button></div></td></tr>)}</tbody></table></div></section></div></>}