import { createFileRoute, Link } from "@tanstack/react-router";
import { Bookmark, CheckCircle2, Clock3, Download, Heart, Upload, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader, SectionHeading, StatCard } from "@/components/kaksha/page-ui";
import { ResourceCard } from "@/components/kaksha/resource-card";
import { resources, subjects } from "@/lib/mock-data";
import { pageMeta } from "@/lib/route-meta";

export const Route = createFileRoute("/dashboard")({ head:()=>pageMeta("Student Dashboard","Track learning, saved resources and contributions on Kaksha Hub."), component:Dashboard });
function Dashboard(){ const stats=[[Upload,"Resources Shared","12","+2 this month"],[CheckCircle2,"Approved","9","75% approval rate"],[Clock3,"Pending","3","Under review"],[Download,"Downloads","2.8k","Across your resources"],[Bookmark,"Saved","34","Ready to revisit"],[Heart,"Helpful Likes","486","From fellow students"]] as const; return <><PageHeader eyebrow="Student workspace" title="Good evening, Student 👋" description="Here’s what’s happening across your CSE Semester 05 study space." actions={<Button asChild><Link to="/contribute"><Upload/>Contribute resource</Link></Button>} /><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{stats.map(([icon,label,value,detail])=><StatCard key={label} icon={icon} label={label} value={value} detail={detail}/>)}</div><section className="mt-16"><SectionHeading eyebrow="Continue learning" title="Pick up where you left off"/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{resources.slice(0,3).map((r)=><ResourceCard key={r.id} resource={r} compact/>)}</div></section><section className="mt-16"><SectionHeading eyebrow="Your semester" title="Your subjects"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{subjects.slice(0,6).map(s=><Link key={s.code} to="/resources" search={{q:"",branch:"CSE",semester:String(s.semester),subject:s.name,type:"",sort:"newest"}} className="flex items-center gap-4 rounded-lg border border-border bg-card p-4 hover:border-primary/30"><span className="grid size-10 place-items-center rounded-md bg-primary/10 text-primary"><UserRound className="size-4"/></span><div><p className="font-semibold">{s.name}</p><p className="text-xs text-muted-foreground">{s.code} · {s.resources} resources</p></div></Link>)}</div></section><section className="mt-16"><SectionHeading eyebrow="For you" title="Recommended resources"/><div className="grid gap-4 md:grid-cols-3">{resources.slice(3).map(r=><ResourceCard key={r.id} resource={r} compact/>)}</div></section><section className="mt-16 rounded-lg bg-ink p-6 text-primary-foreground sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-highlight">Your contributions</p><h2 className="mt-2 font-display text-2xl font-bold">Help the next student learn faster.</h2><p className="mt-2 text-sm text-primary-foreground/65">Share clear notes, useful papers or practical files.</p></div><Button asChild><Link to="/contribute">Share material</Link></Button></div></section></div></>; }