import { createFileRoute, Link } from "@tanstack/react-router";
import { GraduationCap, LockKeyhole, Mail } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { pageMeta } from "@/lib/route-meta";

export const Route=createFileRoute("/login")({head:()=>pageMeta("Log In","Preview the Kaksha Hub student login experience."),component:Login});
function Login(){const [message,setMessage]=useState("");return <AuthFrame title="Welcome back" subtitle="Continue to your academic resource workspace."><form onSubmit={e=>{e.preventDefault();setMessage("Login is coming in Phase 2.")}} className="space-y-4"><label><span className="mb-2 block text-sm font-semibold">Email address</span><span className="relative block"><Mail className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input required type="email" className="h-11 pl-9" placeholder="you@college.edu"/></span></label><label><span className="mb-2 block text-sm font-semibold">Password</span><span className="relative block"><LockKeyhole className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input required type="password" className="h-11 pl-9" placeholder="Enter your password"/></span></label><div className="flex justify-end"><button type="button" className="text-xs font-semibold text-primary">Forgot password?</button></div><Button type="submit" size="lg" className="w-full">Log in</Button>{message&&<p role="status" className="rounded-md bg-primary/10 p-3 text-center text-sm font-semibold text-primary">{message}</p>}<p className="text-center text-sm text-muted-foreground">New to Kaksha Hub? <Link to="/register" className="font-bold text-primary">Create an account</Link></p></form></AuthFrame>}
export function AuthFrame({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="mx-auto grid min-h-[680px] max-w-6xl items-center px-4 py-14 sm:px-6 lg:grid-cols-2 lg:px-8"><div className="hidden h-full min-h-[560px] rounded-l-lg bg-ink p-12 text-primary-foreground lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3 font-display text-xl font-extrabold"><span className="grid size-10 place-items-center rounded-md bg-gradient-brand"><GraduationCap/></span>KAKSHA HUB</div><div><p className="font-display text-4xl font-extrabold leading-tight">Every semester.<br/>Every subject.<br/><span className="text-highlight">One study space.</span></p><p className="mt-5 max-w-sm text-sm leading-relaxed text-primary-foreground/65">Organized AKTU material, contributed by students who understand the syllabus.</p></div><p className="text-xs text-primary-foreground/45">UI preview · Phase 1</p></div><div className="rounded-lg border border-border bg-card p-6 shadow-card sm:p-10 lg:rounded-l-none"><p className="text-xs font-bold uppercase tracking-widest text-primary">KAKSHA HUB</p><h1 className="mt-3 font-display text-3xl font-extrabold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{subtitle}</p><div className="mt-8">{children}</div></div></div>}