import { createFileRoute } from "@tanstack/react-router";
import { Bell, Check, FileCheck2, Sparkles } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/kaksha/page-ui";
import { notifications as initialNotifications } from "@/lib/mock-data";
import { pageMeta } from "@/lib/route-meta";
import { cn } from "@/lib/utils";

export const Route=createFileRoute("/notifications")({head:()=>pageMeta("Notifications","Review Kaksha Hub resource updates and contribution activity."),component:Notifications});
function Notifications(){const [items,setItems]=useState(initialNotifications);const markAll=()=>setItems(current=>current.map(item=>({...item,unread:false})));return <><PageHeader eyebrow="Updates" title="Notifications" description="Stay current with contribution reviews, new material and community milestones." actions={<Button variant="outline" onClick={markAll}><Check/>Mark all as read</Button>}/><div className="mx-auto max-w-3xl px-4 py-12 sm:px-6"> <div className="overflow-hidden rounded-lg border border-border bg-card shadow-card">{items.map((item,index)=><button key={item.id} onClick={()=>setItems(current=>current.map(row=>row.id===item.id?{...row,unread:false}:row))} className={cn("flex w-full cursor-pointer gap-4 border-b border-border p-5 text-left last:border-0 hover:bg-secondary/50",item.unread&&"bg-primary/5")}><span className={cn("grid size-10 shrink-0 place-items-center rounded-full bg-secondary text-muted-foreground",item.unread&&"bg-primary/10 text-primary")}>{index%2?<FileCheck2 className="size-4"/>:<Sparkles className="size-4"/>}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-3"><strong className="text-sm">{item.title}</strong>{item.unread&&<span className="size-2 shrink-0 rounded-full bg-primary"/>}</span><span className="mt-1 block text-sm text-muted-foreground">{item.text}</span><span className="mt-2 block text-xs text-muted-foreground">{item.time}</span></span></button>)}</div><div className="mt-8 flex items-center justify-center gap-2 text-xs text-muted-foreground"><Bell className="size-3.5"/>You’re all caught up.</div></div></>}