import { createFileRoute } from "@tanstack/react-router";
import { Search, SlidersHorizontal } from "lucide-react";
import { z } from "zod";
import { PageHeader, fieldClass } from "@/components/kaksha/page-ui";
import { ResourceCard } from "@/components/kaksha/resource-card";
import { branches, resources, resourceTypes, subjects } from "@/lib/mock-data";
import { pageMeta } from "@/lib/route-meta";

const schema = z.object({ q: z.string().optional(), branch: z.string().optional(), semester: z.string().optional(), subject: z.string().optional(), type: z.string().optional(), sort: z.string().optional() });
export const Route = createFileRoute("/resources/")({ validateSearch: (search) => schema.parse(search), head: () => pageMeta("Resource Library", "Search and filter AKTU notes, papers, assignments, practical files and study material."), component: ResourcesPage });
function ResourcesPage() {
  const search = Route.useSearch(); const navigate = Route.useNavigate();
  const update = (key: keyof typeof search, value: string) => navigate({ search: (previous) => ({ ...previous, [key]: value }) });
  const filtered = resources.filter((item) => (!search.q || `${item.title} ${item.subject} ${item.code}`.toLowerCase().includes(search.q.toLowerCase())) && (!search.branch || item.branch === search.branch) && (!search.semester || String(item.semester) === search.semester) && (!search.subject || item.subject === search.subject) && (!search.type || item.type === search.type)).sort((a, b) => search.sort === "popular" ? b.views - a.views : search.sort === "downloads" ? b.downloads - a.downloads : resources.indexOf(a) - resources.indexOf(b));
  return <><PageHeader eyebrow="Resource library" title="Everything you need to study smarter" description="Search across curated student contributions and narrow results to exactly what your syllabus needs." /><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="rounded-lg border border-border bg-card p-4 shadow-card"><div className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal className="size-4 text-primary" />Filter resources</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6"><label className="relative sm:col-span-2"><span className="sr-only">Search resources</span><Search className="absolute left-3 top-3.5 size-4 text-muted-foreground" /><input className={`${fieldClass} pl-9`} value={search.q ?? ""} onChange={(e) => update("q", e.target.value)} placeholder="Search resources" /></label><Select label="Branch" value={search.branch} onChange={(v) => update("branch", v)} options={branches.map((b) => [b.code, b.code])} /><Select label="Semester" value={search.semester} onChange={(v) => update("semester", v)} options={Array.from({length:8},(_,i)=>[String(i+1),`Semester ${String(i+1).padStart(2,"0")}`])} /><Select label="Subject" value={search.subject} onChange={(v) => update("subject", v)} options={subjects.map((s)=>[s.name,s.name])} /><Select label="Resource type" value={search.type} onChange={(v) => update("type", v)} options={resourceTypes.map((v)=>[v,v])} /><Select label="Sort" value={search.sort ?? "newest"} onChange={(v) => update("sort", v)} options={[["newest","Newest"],["popular","Most viewed"],["downloads","Most downloaded"]]} /></div></div><div className="mt-8 flex items-center justify-between"><p className="text-sm text-muted-foreground"><strong className="text-foreground">{filtered.length}</strong> resources found</p></div>{filtered.length ? <div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((resource) => <ResourceCard key={resource.id} resource={resource} />)}</div> : <div className="mt-6 rounded-lg border border-dashed border-border p-16 text-center"><BookOpenEmpty /></div>}</div></>;
}
function Select({ label, value, onChange, options }: { label:string; value:string | undefined; onChange:(value:string)=>void; options:string[][] }) { return <label><span className="sr-only">{label}</span><select className={fieldClass} value={value ?? ""} onChange={(e)=>onChange(e.target.value)}><option value="">All {label.toLowerCase()}s</option>{options.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>; }
function BookOpenEmpty(){return <><p className="font-display text-lg font-bold">No matching resources</p><p className="mt-2 text-sm text-muted-foreground">Try clearing one or more filters.</p></>}