/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MyResourcesRouteImport } from './routes/my-resources'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SemesterRouteImport } from './routes/semester'
import { Route as ContributorsContributorIdRouteImport } from './routes/contributors.$contributorId'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesResourceIdRouteImport } from './routes/resources.$resourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResourcesRoute = MyResourcesRouteImport.update({
  id: '/my-resources',
  path: '/my-resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SemesterRoute = SemesterRouteImport.update({
  id: '/semester',
  path: '/semester',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorsContributorIdRoute =
  ContributorsContributorIdRouteImport.update({
    id: '/contributors/$contributorId',
    path: '/contributors/$contributorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesResourceIdRoute = ResourcesResourceIdRouteImport.update({
  id: '/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => ResourcesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRoute
  '/my-resources': typeof MyResourcesRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/semester': typeof SemesterRoute
  '/contributors/$contributorId': typeof ContributorsContributorIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRoute
  '/my-resources': typeof MyResourcesRoute
  '/semester': typeof SemesterRoute
  '/contributors/$contributorId': typeof ContributorsContributorIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contribute': typeof ContributeRoute
  '/dashboard': typeof DashboardRoute
  '/my-resources': typeof MyResourcesRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/semester': typeof SemesterRoute
  '/contributors/$contributorId': typeof ContributorsContributorIdRoute
  '/resources/$resourceId': typeof ResourcesResourceIdRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/contribute'
    | '/dashboard'
    | '/my-resources'
    | '/resources'
    | '/semester'
    | '/contributors/$contributorId'
    | '/resources/$resourceId'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/contribute'
    | '/dashboard'
    | '/my-resources'
    | '/semester'
    | '/contributors/$contributorId'
    | '/resources/$resourceId'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/contribute'
    | '/dashboard'
    | '/my-resources'
    | '/resources'
    | '/semester'
    | '/contributors/$contributorId'
    | '/resources/$resourceId'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  ContributeRoute: typeof ContributeRoute
  DashboardRoute: typeof DashboardRoute
  MyResourcesRoute: typeof MyResourcesRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SemesterRoute: typeof SemesterRoute
  ContributorsContributorIdRoute: typeof ContributorsContributorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-resources': {
      id: '/my-resources'
      path: '/my-resources'
      fullPath: '/my-resources'
      preLoaderRoute: typeof MyResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/semester': {
      id: '/semester'
      path: '/semester'
      fullPath: '/semester'
      preLoaderRoute: typeof SemesterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributors/$contributorId': {
      id: '/contributors/$contributorId'
      path: '/contributors/$contributorId'
      fullPath: '/contributors/$contributorId'
      preLoaderRoute: typeof ContributorsContributorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/$resourceId': {
      id: '/resources/$resourceId'
      path: '/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdRouteImport
      parentRoute: typeof ResourcesRoute
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesResourceIdRoute: typeof ResourcesResourceIdRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesResourceIdRoute: ResourcesResourceIdRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  ContributeRoute: ContributeRoute,
  DashboardRoute: DashboardRoute,
  MyResourcesRoute: MyResourcesRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SemesterRoute: SemesterRoute,
  ContributorsContributorIdRoute: ContributorsContributorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
